#pragma once

#define DEV_IMU1            "imu1"
#define DEV_IMU2            "imu2"
#define DEV_MAG1            "mag1"
#define DEV_BARO1           "baro1"
#define DEV_LED0            "led0"
#define DEV_LED1            "led1"
#define DEV_LED2            "led2"
#define DEV_TIMER1          "timer1"
#define DEV_TIMER2          "timer2"
#define DEV_TIMER3          "timer3"
#define DEV_TIMER4          "timer4"
#define DEV_SYSTICK         "systick"
#define DEV_VCOM            "vcom"
#define DEV_USART1          "usart1"
#define DEV_USART2          "usart2"
#define DEV_USART3          "usart3"
#define DEV_USART4          "usart4"
#define DEV_USART5          "usart5"
#define DEV_USART6          "usart6"
#define DEV_USART8          "usart8"
#define DEV_SPI1            "spi1"
#define DEV_SPI4            "spi4"
#define DEV_I2C1            "i2c1"
#define DEV_I2C4            "i2c4"